-- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero

while true do
local descendants = game.Workspace.Washed:GetDescendants()
warn "reading messages (10 second delay to reduce lag)"
wait(5)
    for i, descendants in pairs(descendants) do
        if descendants:IsA("Model") then
            local A_1 = descendants.Name
            local Event = game:GetService("ReplicatedStorage").Remotes.GetNoteInfo
            Event:InvokeServer(A_1)
        end
    end
    print "finished reading"
    wait(5)
end